// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm1ZHAONkpfKv9T74JeWBmcj5rtHpnIRQ',
    appId: '1:226871209394:web:56988ba7b40d47bec488ab',
    messagingSenderId: '226871209394',
    projectId: 'fit-entity-365606',
    authDomain: 'fit-entity-365606.firebaseapp.com',
    databaseURL: 'https://fit-entity-365606-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fit-entity-365606.appspot.com',
    measurementId: 'G-08HMTV7XPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjih7vqj_1gTSWFoVSIUj8tjBrRaiOtLE',
    appId: '1:226871209394:android:ab7256069ca24a6cc488ab',
    messagingSenderId: '226871209394',
    projectId: 'fit-entity-365606',
    databaseURL: 'https://fit-entity-365606-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fit-entity-365606.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU-4Pr7fpC9jdM1nYIwkA5QocEwm5I3nA',
    appId: '1:226871209394:ios:1fb60705a817c263c488ab',
    messagingSenderId: '226871209394',
    projectId: 'fit-entity-365606',
    databaseURL: 'https://fit-entity-365606-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fit-entity-365606.appspot.com',
    iosClientId: '226871209394-avcp53erccbn6cjautfha84sthgitt8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU-4Pr7fpC9jdM1nYIwkA5QocEwm5I3nA',
    appId: '1:226871209394:ios:0f8e804e0a103f75c488ab',
    messagingSenderId: '226871209394',
    projectId: 'fit-entity-365606',
    databaseURL: 'https://fit-entity-365606-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fit-entity-365606.appspot.com',
    iosClientId: '226871209394-b1j1j9t4h8r6u3gtifr128823q0du7st.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutterApp.RunnerTests',
  );
}
